dist: xenial
os: linux
language: node_js
node_js:
  - "13"

services:
  - docker

before_install:
  - docker build -t bkerbil/docker-react -f Dockerfile.dev .

script:
  - echo "Running tests against node $(node -v) and npm $(npm -v) ..."
  - docker run bkerbil/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-956601236526"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"