dist: xenial
os: linux
language: node_js

services:
  - docker

before_install:
  - curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -y nodejs
  - docker build -t bkerbil/docker-react -f Dockerfile.dev .

script:
  - docker run bkerbil/docker-react npm run test -- --coverage